// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimchaFund.Data;

namespace SimchaFund.Data.Migrations
{
    [DbContext(typeof(SimchaDonorContext))]
    [Migration("20190527163808_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimchaFund.Data.Depsit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("DepositDate");

                    b.Property<int>("DonorId");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("deposit");
                });

            modelBuilder.Entity("SimchaFund.Data.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellNumber");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Donor");
                });

            modelBuilder.Entity("SimchaFund.Data.Simcha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("SimchaDate");

                    b.Property<string>("SimchaName");

                    b.HasKey("Id");

                    b.ToTable("Simcha");
                });

            modelBuilder.Entity("SimchaFund.Data.SimchaDonor", b =>
                {
                    b.Property<int>("DonorId");

                    b.Property<int>("SimchaId");

                    b.Property<decimal>("Amount");

                    b.HasKey("DonorId", "SimchaId");

                    b.HasIndex("SimchaId");

                    b.ToTable("SimchaDonor");
                });

            modelBuilder.Entity("SimchaFund.Data.Depsit", b =>
                {
                    b.HasOne("SimchaFund.Data.Donor")
                        .WithMany("Depsits")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SimchaFund.Data.SimchaDonor", b =>
                {
                    b.HasOne("SimchaFund.Data.Donor", "Donor")
                        .WithMany("SimchaDonors")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SimchaFund.Data.Simcha", "Simchas")
                        .WithMany("SimchaDonors")
                        .HasForeignKey("SimchaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
